kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/javad/data  # Directory on your local machine
      containerPath: /mnt/data/minio     # Directory in Kind node (same as in your PV)

  extraPortMappings:
  # Sales-Api
  - containerPort: 3000
    hostPort: 3000
  # Sales-Api debug
  - containerPort: 3010
    hostPort: 3010
  # Metrics
  - containerPort: 4000
    hostPort: 4000
  # Metrics debug
  - containerPort: 4010
    hostPort: 4010
  # Metrics Prometheus
  - containerPort: 4020
    hostPort: 4020
  # Auth
  - containerPort: 6000
    hostPort: 6000
  # Auth debug
  - containerPort: 6010
    hostPort: 6010
  # Grafana
  - containerPort: 3100
    hostPort: 3100
  # Postgres
  - containerPort: 5432
    hostPort: 5432
  # Prometheus
  - containerPort: 9090
    hostPort: 9090
  # Tempo (tracing)
  - containerPort: 9411
    hostPort: 9411
  # MinIO (API)
  - containerPort: 9000
    hostPort: 9000
  # MinIO (console)
  - containerPort: 9001
    hostPort: 9001
  # CrsFront
  - containerPort: 7000
    hostPort: 7000
  # CrsFront debug
  - containerPort: 7010
    hostPort: 7010