// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package profiletempl

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Profile(id string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `business/domain/uinavbarbus/templs/profiletempl/profile.templ`, Line: 4, Col: 13}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"flex cursor-pointer relative items-center gap-2\"><img src=\"/assets/public/icons/UpdateMain/user-b.svg\" alt=\"\"> <span>Ayoub Gharibavi</span> <img src=\"/assets/public/icons/UpdateMain/arrow.svg\" alt=\"\"><div id=\"profile\" class=\"absolute hidden text-[#1D1B20]\"><div class=\"flex text-[#1D1B20] flex-col w-60 gap-5 py-5 z-50 h-max  top-5 px-5 absolute bg-white rounded-lg shadow\"><div class=\"flex border-b pb-2 justify-between\"><div class=\"flex flex-col gap-2\"><span class=\"text-[#605D64]\">Wallet </span><div class=\"flex items-center gap-3\"><span>12,000,000</span><p class=\"text-[#605D64]\">USD</p></div></div><button><img src=\"/assets/public/icons/UpdateMain/add.svg\" alt=\"\"></button></div><div class=\"flex cursor-pointer items-center gap-4\"><img src=\"/assets/public/icons/UpdateMain/acc.svg\" alt=\"\"> <span>Account</span></div><div class=\"flex cursor-pointer items-center gap-4\"><img src=\"/assets/public/icons/UpdateMain/transaction.svg\" alt=\"\"> <span>Transactions</span></div><div class=\"flex cursor-pointer items-center gap-4\"><img src=\"/assets/public/icons/UpdateMain/ticket.svg\" alt=\"\"> <span>Tickets</span></div><div class=\"flex cursor-pointer items-center gap-4\"><img src=\"/assets/public/icons/UpdateMain/support-2.svg\" alt=\"\"> <span>Support</span></div><div class=\"flex cursor-pointer text-[#EE0035] items-center gap-4\"><img src=\"/assets/public/icons/UpdateMain/logout.svg\" alt=\"\"> <span>Log out</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
