apiVersion: v1
kind: Service
metadata:
  name: crsfront-service
  namespace: sales-system

spec:
  type: ClusterIP

  ports:
  - name: crsfront
    port: 7000
    targetPort: crsfront
  - name: crsfront-debug
    port: 7010
    targetPort: crsfront-debug
