apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/crsfront/
  - ./dev-crsfront-configmap.yaml
patches:
  - path: ./dev-crsfront-patch-deploy.yaml
  - path: ./dev-crsfront-patch-service.yaml
images:
  - name: crsfront-image
    newName: localhost/ardanlabs/crsfront
    newTag: 0.0.1
