apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/minio   # Replace with a persistent directory on your host machine
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: sales-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage  # Uses the local-storage provisioner
---
# StatefulSet for MinIO
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: minio-config
          configMap:
            name: minio-conf
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-09-09T16-59-28Z.fips
        args:
          - minio
          - server
          - /data
          - --console-address=:9001
        volumeMounts:
          - name: minio-config
            readOnly: true
            mountPath: /etc/minio
          - name: minio-storage
            mountPath: /data
        envFrom:
          - configMapRef:
              name: minio-conf
        ports:
          - name: api-port
            containerPort: 9000
          - name: console-port
            containerPort: 9001
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "curl -f http://localhost:9000/minio/health/live || exit 1"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "curl -f http://localhost:9000/minio/health/ready || exit 1"
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
# MinIO Service
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api-port
      port: 9000
      targetPort: api-port
    - name: console-port
      port: 9001
      targetPort: console-port
---
# MinIO ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-conf
  namespace: sales-system
data:
  # Environment variables for MinIO
  minio.env: |
    MINIO_ACCESS_KEY=your-access-key
    MINIO_SECRET_KEY=your-secret-key
    MINIO_REGION=us-east-1